services:
  app:
    profiles: ['devcontainer']
    container_name: OCI-Service
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - .:/workspace:cached
    tty: true
    stdin_open: true
    environment:
      DEVCONTAINER: '1'

  api:
    build:
      context: .                    # 프로젝트 루트
      dockerfile: app/Dockerfile
    env_file: .env
    ports:
      - "8000:8000"
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped

  worker:
    build:
      context: .
      dockerfile: worker/Dockerfile
    env_file: .env
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped