"""add retention_days to collection_tickers

Revision ID: 649d89a8d43e
Revises: 7bead3c5cd0d
Create Date: 2026-07-07 08:33:46.203859

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '649d89a8d43e'
down_revision: Union[str, Sequence[str], None] = '7bead3c5cd0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('collection_tickers', sa.Column('retention_days', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('collection_tickers', 'retention_days')
    # ### end Alembic commands ###
