"""add corporate_actions table

Revision ID: f1c30d858eb9
Revises: 649d89a8d43e
Create Date: 2026-07-07 09:09:01.642805

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1c30d858eb9'
down_revision: Union[str, Sequence[str], None] = '649d89a8d43e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('corporate_actions',
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('type', sa.String(length=10), nullable=False),
    sa.Column('value', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.PrimaryKeyConstraint('symbol', 'time', 'type')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('corporate_actions')
    # ### end Alembic commands ###
